# UAH-DriveSet - Raw Accelerometer Analysis

## Objective

The objective of this notebook is to inspect the RAW_ACCELEROMETERS.txt file.

This notebook focuses on:

- Reading the accelerometer data
- Understanding the file structure
- Identifying the available sensor channels
- Checking timestamps
- Performing an initial quality inspection

No preprocessing or machine learning will be performed.

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
dataset_path = "/content/drive/MyDrive/TOGG_Driver_Risk_Project/data/raw/UAH-DRIVESET-v1"

driver_path = os.path.join(dataset_path, "D1")

trip = "20151110175712-16km-D1-NORMAL1-SECONDARY"

trip_path = os.path.join(driver_path, trip)

accelerometer_path = os.path.join(
    trip_path,
    "RAW_ACCELEROMETERS.txt"
)

print(accelerometer_path)

/content/drive/MyDrive/TOGG_Driver_Risk_Project/data/raw/UAH-DRIVESET-v1/D1/20151110175712-16km-D1-NORMAL1-SECONDARY/RAW_ACCELEROMETERS.txt

In [3]:
with open(accelerometer_path, "r") as f:

    for i in range(10):
        print(f.readline())

6.94 1 0.017 -0.011 0.018 -0.005 0.008 0.018 -1.523 0.015 0.012

7.03 1 0.046 0.007 0.019 0.016 -0.002 0.018 -1.522 0.012 0.012

7.14 1 0.052 -0.016 0.027 0.037 -0.005 0.018 -1.520 0.014 0.011

7.24 1 0.015 -0.016 0.026 0.038 -0.009 0.024 -1.523 0.014 0.011

7.34 1 -0.014 -0.017 0.040 0.012 -0.016 0.032 -1.525 0.012 0.011

7.44 1 -0.007 -0.010 0.015 -0.002 -0.006 0.028 -1.525 0.012 0.012

7.54 1 0.007 -0.026 0.027 0.000 -0.024 0.022 -1.527 0.019 0.013

7.64 1 -0.006 -0.021 0.016 -0.002 -0.023 0.022 -1.528 0.018 0.013

7.74 1 -0.009 -0.063 0.032 -0.006 -0.037 0.021 -1.528 0.016 0.014

7.85 1 -0.010 -0.047 0.023 -0.008 -0.044 0.027 -1.527 0.016 0.016

In [4]:
acc_df = pd.read_csv(
    accelerometer_path,
    sep=r"\s+",
    header=None
)

In [5]:
acc_df.head()

     0   1      2      3      4      5      6      7      8      9      10
0  6.94   1  0.017 -0.011  0.018 -0.005  0.008  0.018 -1.523  0.015  0.012
1  7.03   1  0.046  0.007  0.019  0.016 -0.002  0.018 -1.522  0.012  0.012
2  7.14   1  0.052 -0.016  0.027  0.037 -0.005  0.018 -1.520  0.014  0.011
3  7.24   1  0.015 -0.016  0.026  0.038 -0.009  0.024 -1.523  0.014  0.011
4  7.34   1 -0.014 -0.017  0.040  0.012 -0.016  0.032 -1.525  0.012  0.011

In [6]:
acc_df.shape

(6170, 11)

In [7]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6170 entries, 0 to 6169
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6170 non-null   float64
 1   1       6170 non-null   int64
 2   2       6170 non-null   float64
 3   3       6170 non-null   float64
 4   4       6170 non-null   float64
 5   5       6170 non-null   float64
 6   6       6170 non-null   float64
 7   7       6170 non-null   float64
 8   8       6170 non-null   float64
 9   9       6170 non-null   float64
 10  10      6170 non-null   float64
dtypes: float64(10), int64(1)
memory usage: 530.4 KB

In [8]:
acc_df.describe()

,0,1,2,3,4,5,6,7,8,9,10
count,6170.000000,6170.0,6170.000000,6170.000000,6170.000000,6170.000000,6170.000000,6170.000000,6170.000000,6170.000000,6170.000000
mean,318.924016,1.0,-0.011767,-0.000352,-0.001793,-0.011786,-0.000361,-0.001822,-1.554783,-0.014719,-0.576919
std,180.298864,0.0,0.034041,0.035556,0.021682,0.024430,0.031300,0.019112,0.035364,0.041317,0.724366
min,6.940000,1.0,-0.241000,-0.248000,-0.125000,-0.176000,-0.232000,-0.098000,-1.662000,-0.214000,-1.897000
25%,162.575000,1.0,-0.031000,-0.019000,-0.013000,-0.025000,-0.015000,-0.011000,-1.580000,-0.037000,-1.323000
50%,319.010000,1.0,-0.012000,0.000000,-0.001000,-0.012000,0.000000,-0.001000,-1.553000,-0.007000,-0.383000
75%,475.085000,1.0,0.008000,0.020000,0.011000,0.002000,0.016000,0.010000,-1.528000,0.011000,0.129750
max,630.940000,1.0,0.171000,0.173000,0.090000,0.128000,0.149000,0.083000,-1.461000,0.073000,0.547000