In [1]:
import os
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
dataset_path = "/content/drive/MyDrive/TOGG_Driver_Risk_Project/data/raw/UAH-DRIVESET-v1"

print(dataset_path)

/content/drive/MyDrive/TOGG_Driver_Risk_Project/data/raw/UAH-DRIVESET-v1

In [3]:
sample_driver = "D1"

sample_trip = "20151110175712-16km-D1-NORMAL1-SECONDARY"

trip_path = os.path.join(
    dataset_path,
    sample_driver,
    sample_trip
)

print(trip_path)

/content/drive/MyDrive/TOGG_Driver_Risk_Project/data/raw/UAH-DRIVESET-v1/D1/20151110175712-16km-D1-NORMAL1-SECONDARY

In [4]:
lane_path = os.path.join(
    trip_path,
    "PROC_LANE_DETECTION.txt"
)

lane_df = pd.read_csv(
    lane_path,
    sep=r"\s+",
    header=None
)

lane_df.head()

      0    1    2    3  4
0  6.86 -9.0 -9.0 -9.0 -9
1  6.91  0.0 -0.0  3.5 -1
2  7.01  0.0 -0.0  3.5 -1
3  7.04  0.0 -0.0  3.5 -1
4  7.06  0.0 -0.0  3.5 -1

In [5]:
print(lane_df.shape)

lane_df.info()

(15327, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15327 entries, 0 to 15326
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       15327 non-null  float64
 1   1       15327 non-null  float64
 2   2       15327 non-null  float64
 3   3       15327 non-null  float64
 4   4       15327 non-null  int64
dtypes: float64(4), int64(1)
memory usage: 598.8 KB

In [6]:
lane_df.columns = [

    "time",

    "lane_offset",

    "phi",

    "road_width",

    "lane_state"
]

lane_df.head()

   time  lane_offset  phi  road_width  lane_state
0  6.86         -9.0 -9.0        -9.0          -9
1  6.91          0.0 -0.0         3.5          -1
2  7.01          0.0 -0.0         3.5          -1
3  7.04          0.0 -0.0         3.5          -1
4  7.06          0.0 -0.0         3.5          -1

In [7]:
acc_path = os.path.join(
    trip_path,
    "RAW_ACCELEROMETERS.txt"
)

acc_df = pd.read_csv(
    acc_path,
    sep=r"\s+",
    header=None
)

print(acc_df.shape)

acc_df.head()

(6170, 11)

     0   1      2      3      4      5      6      7      8      9      10
0  6.94   1  0.017 -0.011  0.018 -0.005  0.008  0.018 -1.523  0.015  0.012
1  7.03   1  0.046  0.007  0.019  0.016 -0.002  0.018 -1.522  0.012  0.012
2  7.14   1  0.052 -0.016  0.027  0.037 -0.005  0.018 -1.520  0.014  0.011
3  7.24   1  0.015 -0.016  0.026  0.038 -0.009  0.024 -1.523  0.014  0.011
4  7.34   1 -0.014 -0.017  0.040  0.012 -0.016  0.032 -1.525  0.012  0.011

In [8]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6170 entries, 0 to 6169
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6170 non-null   float64
 1   1       6170 non-null   int64
 2   2       6170 non-null   float64
 3   3       6170 non-null   float64
 4   4       6170 non-null   float64
 5   5       6170 non-null   float64
 6   6       6170 non-null   float64
 7   7       6170 non-null   float64
 8   8       6170 non-null   float64
 9   9       6170 non-null   float64
 10  10      6170 non-null   float64
dtypes: float64(10), int64(1)
memory usage: 530.4 KB

In [9]:
def load_lane_detection(lane_path):

    lane_df = pd.read_csv(
        lane_path,
        sep=r"\s+",
        header=None
    )

    lane_df.columns = [

        "time",

        "lane_offset",

        "phi",

        "road_width",

        "lane_state"
    ]

    return lane_df

In [10]:
def clean_lane_detection(lane_df):

    lane_df = lane_df.copy()

    lane_df.replace(-9, np.nan, inplace=True)

    lane_df.replace(-99, np.nan, inplace=True)

    lane_df = lane_df.sort_values(
        "time"
    )

    lane_df = lane_df.reset_index(
        drop=True
    )

    return lane_df

In [11]:
lane_df = load_lane_detection(
    lane_path
)

lane_df = clean_lane_detection(
    lane_df
)

lane_df.head(10)

   time  lane_offset  phi  road_width  lane_state
0  6.86          NaN  NaN         NaN         NaN
1  6.91          0.0 -0.0         3.5        -1.0
2  7.01          0.0 -0.0         3.5        -1.0
3  7.04          0.0 -0.0         3.5        -1.0
4  7.06          0.0 -0.0         3.5        -1.0
5  7.08          0.0 -0.0         3.5        -1.0
6  7.11          0.0 -0.0         3.5        -1.0
7  7.16          0.0 -0.0         3.5        -1.0
8  7.22          0.0 -0.0         3.5        -1.0
9  7.25          0.0 -0.0         3.5        -1.0

In [12]:
print(lane_df.describe())

print()

print(lane_df.isnull().sum())

               time   lane_offset           phi    road_width    lane_state
count  15327.000000  15326.000000  15326.000000  15326.000000  15326.000000
mean     319.495247      0.208492      0.040367      2.768584      1.946300
std      182.517299      0.253543      0.032543      0.176876      0.330189
min        6.860000     -1.433000     -0.129000      2.041000     -1.000000
25%      158.100000      0.081000      0.022000      2.654000      2.000000
50%      324.860000      0.212000      0.041000      2.716000      2.000000
75%      477.825000      0.344000      0.060000      2.884000      2.000000
max      630.980000      1.363000      0.197000      5.501000      2.000000

time           0
lane_offset    1
phi            1
road_width     1
lane_state     1
dtype: int64

In [15]:
def load_gps(gps_path):

    gps_columns = [

        "timestamp",
        "speed",
        "latitude",
        "longitude",
        "altitude",

        "gps_quality",
        "satellites",

        "heading",

        "extra_1",
        "extra_2",
        "extra_3",
        "extra_4"

    ]

    gps_df = pd.read_csv(
        gps_path,
        sep=r"\s+",
        header=None,
        names=gps_columns
    )

    return gps_df

def synchronize_sensors(acc_df, gps_df):

    master_df = pd.merge_asof(

        acc_df.sort_values("timestamp"),

        gps_df.sort_values("timestamp"),

        on="timestamp",

        direction="nearest"

    )

    return master_df

def engineer_features(master_df):

    master_df = master_df.copy()

    # -------------------------------------------------
    # Acceleration Features
    # -------------------------------------------------

    master_df["acc_resultant"] = np.sqrt(
        master_df["acc_x"]**2 +
        master_df["acc_y"]**2 +
        master_df["acc_z"]**2
    )

    master_df["acc_horizontal"] = np.sqrt(
        master_df["acc_x"]**2 +
        master_df["acc_y"]**2
    )

    master_df["acc_vertical"] = master_df["acc_z"]

    # -------------------------------------------------
    # Delta Features
    # -------------------------------------------------

    master_df["speed_delta"] = master_df["speed"].diff().fillna(0)

    master_df["heading_delta"] = master_df["heading"].diff().fillna(0)

    master_df["roll_delta"] = master_df["roll"].diff().fillna(0)

    master_df["pitch_delta"] = master_df["pitch"].diff().fillna(0)

    master_df["yaw_delta"] = master_df["yaw"].diff().fillna(0)

    return master_df

def extract_statistics(signal):

    features = {}

    features["mean"] = signal.mean()

    features["std"] = signal.std()

    features["min"] = signal.min()

    features["max"] = signal.max()

    features["median"] = signal.median()

    features["rms"] = np.sqrt(
        np.mean(signal**2)
    )

    return features

def extract_window_features(window, feature_list):

    window_stats = {}

    for feature in feature_list:

        stats = extract_statistics(window[feature])

        for stat_name, stat_value in stats.items():

            column_name = f"{feature}_{stat_name}"

            window_stats[column_name] = stat_value

    return window_stats

def create_sliding_windows(
        feature_df,
        feature_list,
        window_size
):

    all_window_features = []

    for start in range(
        0,
        len(feature_df) - window_size + 1
    ):

        end = start + window_size

        window = feature_df.iloc[start:end]

        window_stats = extract_window_features(
            window,
            feature_list
        )

        all_window_features.append(window_stats)

    return pd.DataFrame(all_window_features)

def load_accelerometer(acc_path):

    acc_columns = [

        "timestamp",
        "active",

        "acc_x",
        "acc_y",
        "acc_z",

        "acc_x_kf",
        "acc_y_kf",
        "acc_z_kf",

        "roll",
        "pitch",
        "yaw"

    ]

    acc_df = pd.read_csv(
        acc_path,
        sep=r"\s+",
        header=None,
        names=acc_columns
    )

    return acc_df

In [16]:
acc_path = os.path.join(
    trip_path,
    "RAW_ACCELEROMETERS.txt"
)

gps_path = os.path.join(
    trip_path,
    "RAW_GPS.txt"
)

acc_df = load_accelerometer(acc_path)

gps_df = load_gps(gps_path)

master_df = synchronize_sensors(
    acc_df,
    gps_df
)

master_df.head()

,timestamp,active,acc_x,acc_y,acc_z,acc_x_kf,acc_y_kf,acc_z_kf,roll,pitch,...,latitude,longitude,altitude,gps_quality,satellites,heading,extra_1,extra_2,extra_3,extra_4
0,6.94,1,0.017,-0.011,0.018,-0.005,0.008,0.018,-1.523,0.015,...,40.512787,-3.404477,612.7,4,5,331.9,0.0,0,0,0
1,7.03,1,0.046,0.007,0.019,0.016,-0.002,0.018,-1.522,0.012,...,40.512787,-3.404477,612.7,4,5,331.9,0.0,0,0,0
2,7.14,1,0.052,-0.016,0.027,0.037,-0.005,0.018,-1.520,0.014,...,40.512787,-3.404477,612.7,4,5,331.9,0.0,0,0,0
3,7.24,1,0.015,-0.016,0.026,0.038,-0.009,0.024,-1.523,0.014,...,40.512787,-3.404477,612.7,4,5,331.9,0.0,0,0,0
4,7.34,1,-0.014,-0.017,0.040,0.012,-0.016,0.032,-1.525,0.012,...,40.512787,-3.404477,612.7,4,5,331.9,0.0,0,0,0

In [17]:
print(master_df.columns)

print()

print(master_df.shape)

Index(['timestamp', 'active', 'acc_x', 'acc_y', 'acc_z', 'acc_x_kf',
       'acc_y_kf', 'acc_z_kf', 'roll', 'pitch', 'yaw', 'speed', 'latitude',
       'longitude', 'altitude', 'gps_quality', 'satellites', 'heading',
       'extra_1', 'extra_2', 'extra_3', 'extra_4'],
      dtype='object')

(6170, 22)

In [18]:
def merge_lane_data(master_df, lane_df):

    master_df = master_df.copy()
    lane_df = lane_df.copy()

    master_df = master_df.sort_values(
        "timestamp"
    )

    lane_df = lane_df.sort_values(
        "time"
    )

    merged_df = pd.merge_asof(

        master_df,

        lane_df,

        left_on="timestamp",

        right_on="time",

        direction="nearest"

    )

    return merged_df

In [19]:
merged_df = merge_lane_data(
    master_df,
    lane_df
)

merged_df.head()

,timestamp,active,acc_x,acc_y,acc_z,acc_x_kf,acc_y_kf,acc_z_kf,roll,pitch,...,heading,extra_1,extra_2,extra_3,extra_4,time,lane_offset,phi,road_width,lane_state
0,6.94,1,0.017,-0.011,0.018,-0.005,0.008,0.018,-1.523,0.015,...,331.9,0.0,0,0,0,6.91,0.0,-0.0,3.5,-1.0
1,7.03,1,0.046,0.007,0.019,0.016,-0.002,0.018,-1.522,0.012,...,331.9,0.0,0,0,0,7.04,0.0,-0.0,3.5,-1.0
2,7.14,1,0.052,-0.016,0.027,0.037,-0.005,0.018,-1.520,0.014,...,331.9,0.0,0,0,0,7.16,0.0,-0.0,3.5,-1.0
3,7.24,1,0.015,-0.016,0.026,0.038,-0.009,0.024,-1.523,0.014,...,331.9,0.0,0,0,0,7.25,0.0,-0.0,3.5,-1.0
4,7.34,1,-0.014,-0.017,0.040,0.012,-0.016,0.032,-1.525,0.012,...,331.9,0.0,0,0,0,7.32,0.0,-0.0,3.5,-1.0

In [20]:
print(merged_df.shape)

print()

print(merged_df.columns)

(6170, 27)

Index(['timestamp', 'active', 'acc_x', 'acc_y', 'acc_z', 'acc_x_kf',
       'acc_y_kf', 'acc_z_kf', 'roll', 'pitch', 'yaw', 'speed', 'latitude',
       'longitude', 'altitude', 'gps_quality', 'satellites', 'heading',
       'extra_1', 'extra_2', 'extra_3', 'extra_4', 'time', 'lane_offset',
       'phi', 'road_width', 'lane_state'],
      dtype='object')

In [21]:
merged_df[
    [
        "timestamp",
        "lane_offset",
        "phi"
    ]
].head(20)

    timestamp  lane_offset  phi
0        6.94          0.0 -0.0
1        7.03          0.0 -0.0
2        7.14          0.0 -0.0
3        7.24          0.0 -0.0
4        7.34          0.0 -0.0
5        7.44          0.0 -0.0
6        7.54          0.0 -0.0
7        7.64          0.0 -0.0
8        7.74          0.0 -0.0
9        7.85          0.0 -0.0
10       7.95          0.0 -0.0
11       8.04          0.0 -0.0
12       8.14          0.0 -0.0
13       8.24          0.0 -0.0
14       8.34          0.0 -0.0
15       8.44          0.0 -0.0
16       8.54          0.0 -0.0
17       8.64          0.0 -0.0
18       8.74          0.0 -0.0
19       8.85          0.0 -0.0

In [22]:
merged_df = merged_df.drop(
    columns=["time"]
)

merged_df.head()

,timestamp,active,acc_x,acc_y,acc_z,acc_x_kf,acc_y_kf,acc_z_kf,roll,pitch,...,satellites,heading,extra_1,extra_2,extra_3,extra_4,lane_offset,phi,road_width,lane_state
0,6.94,1,0.017,-0.011,0.018,-0.005,0.008,0.018,-1.523,0.015,...,5,331.9,0.0,0,0,0,0.0,-0.0,3.5,-1.0
1,7.03,1,0.046,0.007,0.019,0.016,-0.002,0.018,-1.522,0.012,...,5,331.9,0.0,0,0,0,0.0,-0.0,3.5,-1.0
2,7.14,1,0.052,-0.016,0.027,0.037,-0.005,0.018,-1.520,0.014,...,5,331.9,0.0,0,0,0,0.0,-0.0,3.5,-1.0
3,7.24,1,0.015,-0.016,0.026,0.038,-0.009,0.024,-1.523,0.014,...,5,331.9,0.0,0,0,0,0.0,-0.0,3.5,-1.0
4,7.34,1,-0.014,-0.017,0.040,0.012,-0.016,0.032,-1.525,0.012,...,5,331.9,0.0,0,0,0,0.0,-0.0,3.5,-1.0

In [26]:
def engineer_features_v2(master_df):

    master_df = master_df.copy()

    # -------------------------------------------------
    # Acceleration Features
    # -------------------------------------------------

    master_df["acc_resultant"] = np.sqrt(
        master_df["acc_x"]**2 +
        master_df["acc_y"]**2 +
        master_df["acc_z"]**2
    )

    master_df["acc_horizontal"] = np.sqrt(
        master_df["acc_x"]**2 +
        master_df["acc_y"]**2
    )

    master_df["acc_vertical"] = master_df["acc_z"]

    # -------------------------------------------------
    # Delta Features
    # -------------------------------------------------

    master_df["speed_delta"] = master_df["speed"].diff().fillna(0)

    master_df["heading_delta"] = master_df["heading"].diff().fillna(0)

    master_df["roll_delta"] = master_df["roll"].diff().fillna(0)

    master_df["pitch_delta"] = master_df["pitch"].diff().fillna(0)

    master_df["yaw_delta"] = master_df["yaw"].diff().fillna(0)

    return master_df

In [27]:
window_features_v2 = [

    "acc_resultant",
    "acc_horizontal",

    "speed",
    "speed_delta",

    "roll",
    "pitch",
    "yaw",

    # Yeni Lane Features
    "lane_offset",
    "phi"

]

print(window_features_v2)

['acc_resultant', 'acc_horizontal', 'speed', 'speed_delta', 'roll', 'pitch', 'yaw', 'lane_offset', 'phi']

In [33]:
def create_sliding_windows_v2(
    feature_df,
    feature_list,
    window_size
):

    all_window_features = []

    for start in range(
        0,
        len(feature_df) - window_size + 1
    ):

        end = start + window_size

        window = feature_df.iloc[start:end]

        window_stats = extract_window_features_v2(
            window,
            feature_list
        )

        all_window_features.append(
            window_stats
        )

    return pd.DataFrame(
        all_window_features
    )
def extract_window_features_v2(window, feature_list):

    window_stats = {}

    for feature in feature_list:

        stats = extract_statistics_v2(window[feature])

        for stat_name, stat_value in stats.items():

            column_name = f"{feature}_{stat_name}"

            window_stats[column_name] = stat_value

    return window_stats

def extract_statistics_v2(signal):

    features = {}

    # ------------------------------
    # Basic Statistics
    # ------------------------------

    features["mean"] = signal.mean()
    features["std"] = signal.std()
    features["variance"] = signal.var()

    features["min"] = signal.min()
    features["max"] = signal.max()

    features["median"] = signal.median()

    features["rms"] = np.sqrt(
        np.mean(signal ** 2)
    )

    # ------------------------------
    # Distribution Shape
    # ------------------------------

    features["skewness"] = signal.skew()

    features["kurtosis"] = signal.kurt()

    # ------------------------------
    # Percentiles
    # ------------------------------

    features["q25"] = signal.quantile(0.25)

    features["q75"] = signal.quantile(0.75)

    features["iqr"] = (
        features["q75"] -
        features["q25"]
    )

    return features

In [ ]:
feature_df = engineer_features_v2(
    merged_df
)

window_dataset = create_sliding_windows_v2(
    feature_df,
    window_features_v2,
    60
)

print(window_dataset.shape)

window_dataset.head()

(6111, 108)

,acc_resultant_mean,acc_resultant_std,acc_resultant_variance,acc_resultant_min,acc_resultant_max,acc_resultant_median,acc_resultant_rms,acc_resultant_skewness,acc_resultant_kurtosis,acc_resultant_q25,...,phi_variance,phi_min,phi_max,phi_median,phi_rms,phi_skewness,phi_kurtosis,phi_q25,phi_q75,phi_iqr
0,0.052610,0.022257,0.000495,0.019339,0.118106,0.048171,0.057052,0.794801,0.456685,0.034369,...,0.000656,-0.035,0.107,-0.0,0.029030,1.578063,2.825057,-0.0,0.026,0.026
1,0.052771,0.022104,0.000489,0.019339,0.118106,0.048171,0.057142,0.809346,0.504046,0.035270,...,0.000652,-0.035,0.107,-0.0,0.029095,1.562977,2.819787,-0.0,0.026,0.026
2,0.052418,0.022313,0.000498,0.019339,0.118106,0.046448,0.056897,0.814978,0.446186,0.034369,...,0.000653,-0.035,0.107,-0.0,0.029095,1.562507,2.815531,-0.0,0.026,0.026
3,0.052048,0.022357,0.000500,0.019339,0.118106,0.045901,0.056573,0.856475,0.479302,0.034369,...,0.000664,-0.035,0.107,-0.0,0.029160,1.531093,2.711391,-0.0,0.026,0.026
4,0.052207,0.022260,0.000496,0.019339,0.118106,0.045901,0.056681,0.853881,0.508790,0.035270,...,0.000666,-0.035,0.107,-0.0,0.029162,1.529433,2.698166,-0.0,0.026,0.026